### ISSUE TITLE
Backbone.AssociatedModel not populating

### ISSUE THREAD

**Issue by allenwyma** [dhruvaray/backbone-associations#18]
I came over from Backbone-relational, because I thought it was broken, but this also seems to not be working correctly.

I have a key in my model, 'jobs' and when I use model.get('jobs') it is coming in as undefined. Strange thing is that IT DOES have this when I use console.log(model.attributes). I can see it has a jobs array, but it doesn't seem to parse it correctly. I'm using coffeescript:

``` coffeescript
class SomeNamespace.Models.User extends Backbone.AssociatedModel

  relations: [
    type: Backbone.Many
    key: 'jobs'
    relatedModel:SomeNamespace.Models.Job
  ]

  urlRoot: '/users'
```

Do I also have to make a collection for this to work?

**Comment by jdkanani** [comment]
No. You don't need to make a collection. I am unable to reproduce your problem. See this [fiddle](http://jsfiddle.net/jdkanani/LkmMY/). `model.get('jobs')` comes fine.. I have written this on backbone v0.9.10 and backbone-associations (edge version). But it should also work on previous versions.

**Comment by allenwyma** [comment]
Actually, can go ahead and close this. Turns out my server was returning a 2 dimmensional array. I had to correct server side for it to work. Thanks for your help, though. Just to clarify, I can use extends with Coffeescript and don't need to call setup() at the end of my model like Backbone-relational?

**Comment by dhruvaray** [comment]
I have not really worked on coffeescript. But no - you don't need to call setup. There is no such API in backbone-associations. See my quick and dirty coffeescript [fiddle](http://jsfiddle.net/dhruvaray/scb4T/) using `AssociatedModel`s

**Comment by chesterxgchen** [comment]
> > See this fiddle (http://jsfiddle.net/jdkanani/LkmMY/). model.get('jobs') comes fine..

I just tried above mentioned scripts in fiddle, it doesn't seem to work. I have the same problem with the latest version i download yesterday. It could be just that I don't know how to use it.  But again, the fiddle example doesn't work for me either. 

The key problem for me is that the documentation doesn't have an example as to how to populate the model once the model is defined. 

In the fiddle example, user -> many jobs , for each user model, the jobs the populated via overwrite a sync method, is this recommended method ? 

A complete working example in the documentation on GitHub would be very helpful.

**Comment by jdkanani** [comment]
I have updated [fiddle](http://jsfiddle.net/jdkanani/LkmMY/) with changed API of latest Backbone. It should work now.

> In the fiddle example, user -> many jobs , for each user model, the jobs the populated via overwrite a sync method, is this recommended method ? 

 Custom [sync](http://backbonejs.org/#Model-sync) is just to show how fetch/save works. It provides sample data for model/collection to play with. You don't need to do that in your application.

> The key problem for me is that the documentation doesn't have an example as to how to populate the model once the model is defined
1. `model.fetch()` - which will [fetch](http://backbonejs.org/#Model-fetch) model data from server with [defined url](http://backbonejs.org/#Model-url) and populate  `model` with received data.
2. Use `model.save()` - which will [update/create](http://backbonejs.org/#Model-save) model.

Hope this makes it clear. Let me know if you are able to populate your models.

And yes, we will update our docs with working example very soon.

**Comment by chesterxgchen** [comment]
Thanks for the quick response, the jsfiddle example works now. 

Regarding to the fetch() and save(), this is still not clear for me.  The normal backbone model without association will only fetch the data itself. for example, User.fetch will only fetch user, userCollection will fetch a collection of users. 
With User-> job association, when I call user.fetch. does the model expect the backend API to do " deep fetch " and return the both user and jobs ?  or do a shallow fetch to only fetch the users; if the that's the case, should I overwrite the User sync function to fetch the jobs on demand ? 

For deep fetch, how to control the pagination if the association has a lot of data ? 

If it is shallow fetch, where do I specify the API Url for the jobs  for example, users/:id/jobs ?
How do I control the deep or shallow behavior ? 

A complete example and some explanation will help in this regards.

**Comment by dhruvaray** [comment]
@chesterxgchen : You may want to take a look at the new [documentation and recipes](http://dhruvaray.github.io/backbone-associations/) for your queries...
